apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-api.fullname" . }}
  labels:
    {{- include "backend-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "backend-api.databaseUrl" . | quote }}
  redis-url: {{ include "backend-api.redisUrl" . | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  jwt-access-expiry: {{ .Values.secrets.jwtAccessExpiry | quote }}
  jwt-refresh-expiry: {{ .Values.secrets.jwtRefreshExpiry | quote }}
  {{- if .Values.secrets.githubClientId }}
  github-client-id: {{ .Values.secrets.githubClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.githubClientSecret }}
  github-client-secret: {{ .Values.secrets.githubClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientId }}
  google-client-id: {{ .Values.secrets.googleClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientSecret }}
  google-client-secret: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpUser }}
  smtp-user: {{ .Values.secrets.smtpUser | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPass }}
  smtp-pass: {{ .Values.secrets.smtpPass | quote }}
  {{- end }}
  {{- if .Values.secrets.sentryDsn }}
  sentry-dsn: {{ .Values.secrets.sentryDsn | quote }}
  {{- end }}
  {{- if .Values.secrets.ipinfoToken }}
  ipinfo-token: {{ .Values.secrets.ipinfoToken | quote }}
  {{- end }}
