# ==============================================
# Development Deployment Patch
# ==============================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        environment: dev
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "development"
