// Source of truth for site routes consumed by build-sitemap.mjs,
// indexnow-submit.mjs, and (future) prerender plugin.
//
// Until the A1 prerender + route-split refactor lands, only `/` is
// physically served as a discrete URL. New routes added here MUST also
// be added to React Router and the prerender config; otherwise the
// sitemap will advertise URLs that 404 (or that all serve the SPA
// shell — equivalent from a crawler's perspective).

export const SITE_ORIGIN = "https://thulanimaseko.co.za";

/** @type {Array<{path: string, priority: number, changefreq: string}>} */
export const STATIC_ROUTES = [
  { path: "/", priority: 1.0, changefreq: "monthly" },
  // Statically-generated content indexes — produced by build-static-pages.mjs.
  // Individual posts are picked up from dist/content-manifest.json by
  // build-sitemap.mjs at run time (not hardcoded here).
  { path: "/blog", priority: 0.7, changefreq: "weekly" },
  { path: "/answers", priority: 0.8, changefreq: "weekly" },
  { path: "/projects", priority: 0.9, changefreq: "weekly" },
];

// Minimum URL count enforced by build-sitemap.mjs. Bump as routes grow.
export const MIN_SITEMAP_URLS = 4;

// IndexNow key — value matches the public/<key>.txt filename. Rotating
// requires renaming the .txt file AND updating this constant in the
// same commit.
export const INDEXNOW_KEY = "00b81fad70da4ae7acdbfd756d25c510";

// ---------------------------------------------------------------------------
// Analytics — self-hosted Umami on the homelab, reached through a Cloudflare
// Tunnel. First-party (own domain, own server, own database), cookieless, and
// no third-party processor. See homelab-infra/apps/umami/README.md.
//
// ANALYTICS_ORIGIN must stay in lockstep with BOTH:
//   - `script-src` / `connect-src` in src/worker.ts  (or the browser silently
//     refuses to load the tracker AND refuses to send the beacon)
//   - the tunnel's ingress hostname in homelab-infra/apps/umami/cloudflared.yaml
// domainConsistency.test.ts enforces the worker.ts half of that.
export const ANALYTICS_ORIGIN = "https://t.thulanimaseko.co.za";

// Generated by Umami when the site is created in its dashboard — see step 5 of
// homelab-infra/apps/umami/README.md. Left as a non-UUID placeholder on purpose:
// domainConsistency.test.ts asserts this is a real UUID, so CI stays red until
// the value is filled in. Shipping the placeholder would make Umami reject every
// beacon with a 400 that nothing on the site surfaces.
export const ANALYTICS_WEBSITE_ID = "SET_ME_AFTER_UMAMI_FIRST_RUN";

// Hostnames the tracker is allowed to report from. Umami compares this list
// against `location.hostname` exactly — no www-stripping, no suffix matching.
//
// BOTH apex and www are required: wrangler.toml:43-51 binds them as two separate
// custom domains and there is NO www -> apex redirect anywhere (see
// src/https-redirect.ts, which only handles http -> https). Listing the apex
// alone would silently drop every visitor who typed or pasted a www URL —
// exactly the recruiter traffic this exists to measure.
//
// thulani-portfolio.masekotlg.workers.dev is deliberately absent: it stays live
// as a fallback and CI asserts against it, so including it would file synthetic
// CI traffic as real visits.
export const ANALYTICS_DOMAINS = ["thulanimaseko.co.za", "www.thulanimaseko.co.za"];

/**
 * The two analytics <script> tags, shared by every generated page.
 *
 * index.html carries a hand-written fourth copy (it is not produced by any
 * script) — keep the two in sync; domainConsistency.test.ts cross-checks them.
 *
 * `data-domains` makes the tracker no-op on any hostname other than the live
 * site, so `npm run dev`, `npm run preview` and Lighthouse runs never pollute
 * the data. That is why no build-time gating is needed.
 */
export function analyticsTags() {
  return [
    `<script defer src="${ANALYTICS_ORIGIN}/script.js" data-website-id="${ANALYTICS_WEBSITE_ID}" data-domains="${ANALYTICS_DOMAINS.join(",")}"></script>`,
    `<script type="module" src="/outbound.js"></script>`,
  ].join("\n    ");
}
