// The site's domain is a literal string duplicated in three independent
// places with no import relationship between them:
//   - scripts/seo/routes.mjs      (feeds sitemap.xml, rss.xml, indexnow)
//   - scripts/seo/page-template.mjs (feeds generated blog/answers/projects pages)
//   - src/seo/schemaBuilders.ts   (not yet wired into any page — see its own
//     header comment — but is the schema.org canonical reference schemaBuilders.test.ts
//     asserts against, and the copy page-template.mjs's own comment says to
//     keep in lockstep)
// index.html adds a fourth, hand-written copy (canonical, hreflang, OG,
// JSON-LD @id, Plausible data-domain) that isn't generated by any script at all.
//
// schemaBuilders.test.ts and pageTemplate.test.ts each compare a module's
// output against a literal copied from that SAME module — they prove a file
// is internally consistent, never that the four copies agree with each
// other. A rename that updates three of four ships a broken JSON-LD entity
// graph (mismatched @id across documents) with every existing test green.
// This file is the cross-check those tests don't do.

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { SITE_ORIGIN as ROUTES_ORIGIN } from "../../scripts/seo/routes.mjs";
import { renderPage } from "../../scripts/seo/page-template.mjs";
import { buildBlogPosting } from "./schemaBuilders";

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexHtml = readFileSync(
  resolve(__dirname, "../../index.html"),
  "utf-8",
);

describe("domain consistency across independent SITE_ORIGIN copies", () => {
  it("routes.mjs SITE_ORIGIN is a well-formed https origin with no trailing slash", () => {
    // Every consumer below string-concatenates onto this value; a trailing
    // slash or bare hostname would double up or break every URL built from it.
    expect(ROUTES_ORIGIN).toMatch(/^https:\/\/[^/]+$/);
  });

  it("page-template.mjs agrees with routes.mjs", () => {
    const html = renderPage({
      kind: "blog",
      slug: "domain-check",
      title: "t",
      description: "d",
      datePublished: "2026-01-01T00:00:00Z",
      htmlBody: "<p>x</p>",
    });
    expect(html).toContain(
      `<link rel="canonical" href="${ROUTES_ORIGIN}/blog/domain-check" />`,
    );
  });

  it("schemaBuilders.ts agrees with routes.mjs", () => {
    const out = buildBlogPosting({
      slug: "domain-check",
      headline: "t",
      description: "d",
      datePublished: "2026-01-01T00:00:00Z",
      image: `${ROUTES_ORIGIN}/og/x.png`,
    });
    expect(out["@id"]).toBe(`${ROUTES_ORIGIN}/blog/domain-check#blogposting`);
  });

  it("index.html's canonical link agrees with routes.mjs", () => {
    expect(indexHtml).toContain(
      `<link rel="canonical" href="${ROUTES_ORIGIN}/" />`,
    );
  });

  it("index.html's Person @id agrees with routes.mjs", () => {
    // This is the anchor every generated page's JSON-LD author/publisher
    // reference points back at. If it drifts from the other three copies,
    // the entity graph splits silently — no build error, just broken
    // disambiguation for crawlers.
    expect(indexHtml).toContain(`"@id": "${ROUTES_ORIGIN}/#thulani"`);
  });

  it("index.html's Plausible data-domain agrees with routes.mjs", () => {
    // A mismatch here doesn't error, it just silently stops recording
    // analytics — no unit test catches "recorded zero events" any other way.
    const host = new URL(ROUTES_ORIGIN).host;
    expect(indexHtml).toContain(`data-domain="${host}"`);
  });
});
